[package]
name = "GitSpace"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.27", features = ["wgpu"] }
egui = "0.27"
git2 = "0.18"
poll-promise = "0.3"
reqwest = { version = "0.12", features = ["blocking", "json"] }
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
